### PR TITLE
fix CI and remove EOL ubuntu

### PR DESCRIPTION
**Pull request by wkloucek**

### CODE REVIEW

**Comment by wkloucek** [comment]
@micbar @jnweiger what do you think about this?

**Comment by micbar** [comment]
why build a 10.6.0 on Ubuntu 18.04?

**Comment by wkloucek** [comment]
> why build a 10.6.0 on Ubuntu 18.04?

18.04 is LTS and still supported until 2024. Also this is our only running arm32v7 build.

**Comment by micbar** [comment]
hmm, Ubuntu 18.04 has two known issues, this is the reason why we used 19.10

- smbclient lib is too old, doesn't work
- SSO with SAML is not possible due to broken dependencies for apache.

**Comment by wkloucek** [comment]
Ok didn't know this. Sounds like we should not release it with Ubuntu 18.04

**Comment by xoxys** [comment]
@wkloucek @micbar I guess we should use current LTS 20.04 now?

**Comment by micbar** [comment]
yes. 20.04 is the standard ownCloud Deployment.

**Comment by wkloucek** [comment]
> yes. 20.04 is the standard ownCloud Deployment.

Should be fine now. Please review so that we can merge #138

**Review by xoxys — APPROVED** [review]

**Pull request merged**
