### PR TITLE
Use custom path within owncloud installation ...

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes https://github.com/owncloud/theme-enterprise/issues/5
see https://github.com/owncloud/theme-enterprise/issues/5#issuecomment-324282639

### CODE REVIEW

**Comment by tboerger** [comment]
You know that the custom folder is just a symlink to exactly this folder? Are you sure that this fixes it?

**Comment by DeepDiver1975** [comment]
> You know that the custom folder is just a symlink to exactly this folder? Are you sure that this fixes it?

yes - read the issue

**Comment by tboerger** [comment]
Sounds more like a workaround but whatever.

**Comment by DeepDiver1975** [comment]
> Sounds more like a workaround but whatever.

we for sure need to fix this in core - see https://github.com/owncloud/core/issues/28778

but this fix will make the docker images work properly now

**Pull request merged**
