### PR TITLE
Add option for OWNCLOUD_ALLOW_EXTERNAL_LOCAL_STORAGE

### PR DESCRIPTION
**Pull request by vkhurana**
This allows docker containers to override the specific config.php option to allow Local folders to be mounted in external storage.

The option was added in config.php (and disabled by default) with PR#27590 (https://github.com/owncloud/core/pull/27590)

This PR adds a Environment Variable that allows containers to set that value in config.php

### CODE REVIEW

**Comment by vkhurana** [comment]
This would be useful for people that want to deploy OwnCloud using docker, and want to mount local storage. Currently, the owncloud instance needs to be edittied manually to allow Local Mounts.

**Comment by tboerger** [comment]
This can already be done with an occ command, but beside that I would prefer to have an empty default value and call occ if the value is true or false.

**Comment by vkhurana** [comment]
@tboerger Thanks for the feedback!

I agree with your comments. I have updated it to take effect using the occ command.

I've made the changes in rootfs/etc/owncloud.d/90-services.sh but if you think it would be more suited in a different file, please let me know.

**Comment by vkhurana** [comment]
@tboerger thanks!

**Comment by patrickjahns** [comment]
Right now it is missing the case, when `OWNCLOUD_ALLOW_EXTERNAL_LOCAL_STORAGE` was once defined, but in a successive container start removed

**Comment by vkhurana** [comment]
@patrickjahns that's a good point - should we default it to false, to prevent that case?

**Comment by tboerger** [comment]
IMHO it's fine like it is... If somebody drops the option it's up to him to drop this flag. Otherwise we would also the behavior of existing installations

**Comment by patrickjahns** [comment]
@tboerger 
merge?

**Pull request merged**
