### PR TITLE
Create smb.conf

### PR DESCRIPTION
**Pull request by voroyam**
we have to add this file for the smb client to work.

### CODE REVIEW

**Comment by voroyam** [comment]
> Is `TUX-NET` really a useful default? :)

No idea. We could change it to something different :)

**Comment by patrickjahns** [comment]
@voroyam 
Do you have a suggestion for a better name?

**Comment by tboerger** [comment]
I think the default is `WORKGROUP`.

**Comment by voroyam** [comment]
This is the default sample minimum config from somewhere /usr/share/ in Ubuntu. But I can change the name to WORKGROUP

**Comment by voroyam** [comment]
I can't merge this, @tboerger can you merge?

**Comment by tboerger** [comment]
Please also cherry-pick the change for the xenial and bionic branches.

**Comment by voroyam** [comment]
Don't know how to cherry pick. Can we do this Monday in the office?

**Comment by tboerger** [comment]
```
git checkout xenial
git checkout -b xenial-smb-config
git cherry-pick 6ae192d45c0a3284d3746bb64fccd628642e0607
git cherry-pick f94192655a177465d362aa855a845f635ecf7cac
git push -u origin xenial-smb-config
```

:)

**Comment by voroyam** [comment]
did you already done this commands or should I do them?

**Comment by patrickjahns** [comment]
@voroyam 
NO it wasn't done yet - he provided you with the steps to learn how to do it.

Keep in mind - above is for `xenial` branch - same steps needed for `bionic`

**Comment by voroyam** [comment]
@patrickjahns Okay, I just thought that if he copy/pasted it from his terminal, he probably executed those commands. Would make sense to me.

**Comment by tboerger** [comment]
I didn't copy paste that, these are the commands directly from my mind ;)

**Comment by voroyam** [comment]
https://github.com/owncloud-docker/base/pull/93

https://github.com/owncloud-docker/base/pull/94

**Pull request merged**
