### PR TITLE
feat: remove loglevel default to allow runtime changes

### PR DESCRIPTION
**Pull request by jnweiger**
In the current implementation, environment variables take precedence over
runtime changes. That results in bad UX, hampers support for docker deployments and was reported 
in e.g. https://github.com/owncloud/core/issues/38535 (but dismissed).

Here I present a (partial) solution to encourage reconsideration.

With loglevel, the situation is especially bad, as a default value of
"2" is hardcoded to the environment variables, which renders the
tests in override-config.php ineffective. Thus runtime changes are
not possible in a docker deployment at all.

The expectated behaviour is, that the loglevel can be set at runtime via

* admin settings UI
* occ log:manage --level=XXXX
* editing config.php

Currently these are silently ignored in docker deployments, both, when (a)
OWNCLOUD_LOGLEVEL was specified in the docker env at startup, and also
(b) when it was not even specified.

This is a minimal one-liner fix, to no longer "enforce a default" value. (owncloud defaults to "2" anyway, when no loglevel is set)
With this fix, UI, occ and config.php work normally in case (b).

The complete fix -- including (a) -- should make the environment to have lower in precedence than runtime settings.
(A naive `empty($CONFIG['loglevel']) && ...;` did not work for me.)

### CODE REVIEW

**Comment by cdamken** [comment]
Cool, this fix the issue, by default is already the log level set in 2 and then we can change as desired.

Otherwise, we have to do CSS magic and point to the documentation where it will explain how to change it.

@micbar, @pmaier1 and @xoxys are you agree??  This helps us in support a lot!

**Comment by micbar** [comment]
IMO it should work like this:

1) Docker ENV variable should take precedence
2) You should be able to temporarlily set it in the UI
3) After restart of the docker container the change should be gone

@jnweiger @cdamken @xoxys

**Comment by xoxys** [comment]
> IMO it should work like this: 

Correct, but this needs IMO a more general rework of how env vars are used within the docker image...

**Comment by cdamken** [comment]
> IMO

Exactly, it's an opinion, I need a solution. Sad that we have to fork ourselves because we can agree in a small stuff.

**Comment by micbar** [comment]
Hacking stuff together "somehow"  also doesn't fix the problem 😄 

It just creates more 🙈

**Comment by micbar** [comment]
The main evil of the whole thing is that the setting is persisted in the Config.php

**Comment by cdamken** [comment]
You asked for an easy and good fix, we could agree that this is helpful from everyone and doesn't damage anything.

Or are we playing like this?: My toy, my rules.

**Comment by micbar** [comment]
Calm down please! @xoxys is the maintainer of this. We can find a good solution.

**Comment by jnweiger** [comment]
> IMO it should work like this:
> 
>     1. Docker ENV variable should take precedence
> 
>     2. You should be able to temporarlily set it in the UI
> 
>     3. After restart of the docker container the change should be gone
> 
> 
> @jnweiger @cdamken @xoxys

I disagree with 1) as that prevents 2). Docker ENV should provide the default ontop of which UI and occ take precedence.

This PR implements 2) for the most frequent case (start with default) when 1) is not needed.

3) is fine with me. I  don't have strong opinion on this.

**Comment by micbar** [comment]
> > IMO it should work like this:
> > ```
> > 1. Docker ENV variable should take precedence
> > 
> > 2. You should be able to temporarlily set it in the UI
> > 
> > 3. After restart of the docker container the change should be gone
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @jnweiger @cdamken @xoxys
> 
> I disagree with 1) as that prevents 2). Docker ENV should provide the default ontop of which UI and occ take precedence.
> 
> This PR implements 2) for the most frequent case (start with default) when 1) is not needed.
> 
> Item 3) is fine with me. I don't have strong opinion on this.

I do not agree. In a docker deployment always expect, that the ENV var is overriding.

**Comment by micbar** [comment]
This is how it is designed, please read the code comment

https://github.com/owncloud/core/blob/d3c4ed58ca1e87e469d3cd8c79b4d6dca38264ac/lib/private/Config.php#L78-L100

**Comment by micbar** [comment]
with this PR we would change the behavior in the following way:

## Case 1
- config.php is set to `2`
- ENV var is empty

-> User change in the admin UI has an effect
-> will it be set back after restart? Needs to be tested.

## Case 2
- config.php is set to `2`
- ENV var is set to `1`

-> User change in the admin UI has **no** effect

**Comment by micbar** [comment]
needs more thinking.

**Comment by jnweiger** [comment]
I'd like to distinguish two cases. 

a) `docker run -e OWNCLOUD_LOGLEVEL=4 owncloud/server:10.7.0` -- I can accept that the docker env takes precedence and maybe even blocks the UI. Bad UX can be fixed with CSS workarounds, but I'd rather look into allowing temporary changes -- I have not yet provided a solution to that.

b) `docker run owncloud/server:10.7.0` - The UI (and occ commands) should work. No "override" was specified through docker env. -- I have provided a fix for this case. And that is all that this PR asks for.

Robert's argument was that we should either fix both or none, as history tells us that accepting a partial fix usually takes away the pressure to do the correct fix.
I'l do some more investigation to find the least intrusive complete fix -- you may want to wait for that.

But if that gets difficult. I'd still argue that the benefit for support and QA is worth a well informed discussion.

**Comment by xoxys** [comment]
> Robert's argument was that we should either fix both or none

That's just half of my argument. The other half part is https://github.com/owncloud-docker/base/pull/149#issuecomment-843221872 I'm still not convinced that the current approach is the right way to go. Create an issue and we will look into it. I also still don't understand the pressure right now. This behavior exists for years, and now it hurts that much that we would like to merge a partial fix without a chance to verify a general solution? Again, I don't dictate the rules in this GH Orga, if someone else with the required permissions want to approve and merge this PR go on. I'll not.

**Comment by jnweiger** [comment]
No time pressure from my side. I am already very happy, that we can actually discuss the not-so-holy-grail of our docker setup at all.

**Comment by xoxys** [comment]
From what I've seen after short testing that issue is completely regardless of using docker or not (e.g. we will see the same behavior using our ansible roles to deploy containerless oC). Reason:

To pre-provision/autoconfigure ownCloud we always use an `config/custom.config.php` file to not mess up the default `config.php` as this file holds important values like the instance id/salt/etc. As these files are generated by ownCloud it's not that simple to use any kind of config management solution to write into the same file. That's the reason why we always use a standalone file which is not controlled by the ownCloud itself. But with a minimal `custom.config.php` like this, you will no longer be able to temp. change this option in the UI:

```PHP
<?php
$CONFIG = array (
  'loglevel' => 1,
);
```

We have to agree on at least one general thing: If you use a config mgmt or docker, this is the only source of truth. That means whatever someone do in the UI during runtime it has to be reverted by the defined config e.g. Docker env var on next startup. Otherwise, it breaks the whole idea. 

But the problem is, to allow temp. changes in the UI at the same time which is hard to achieve. The workaround by this PR does only work as long as no the env var is not set. But how to handle settings where **need/want** to set another default value because its important or just makes more sense in a docker environment? In this case we have to set a default for the env var and the UI is broken again as it will again reset UI changes immediately.

**Comment by micbar** [comment]
Proposal: completely remove the UI in ownCloud.

Reasoning: 
1) clicking a button in the UI should never change the `config.php` (breaks automated deployments)
2) The override mechanism is not transparent to the user

We should apply KISS rules here:
- One way to change the loglevel 
- done

**Comment by xoxys** [comment]
How do you want to disable the UI? Maintaining PHP templates to remove parts from the UI is a pain as well.

**Comment by micbar** [comment]
> How do you want to disable the UI? Maintaining PHP templates to remove parts from the UI is a pain as well.

Completely remove the UI Element from the product.

**Comment by xoxys** [comment]
ou mean from ownCloud Server itself? Agree even if I don't believe it until it's done :rofl:

**Comment by micbar** [comment]
KISS principle https://en.wikipedia.org/wiki/KISS_principle

I don't get the Use Case of that UI element. If you want to change loglevel, then i assume you want to read logfiles. If you want to read logfiles, you should have shell access or are able to manage the container.
Sounds logical?

**Comment by xoxys** [comment]
Well someone may argue that the log level can be changed via UI is useful as you can still download the log file from the UI as well. Besides that, its still not just the log level, there are multiple other settings with the exact same conflict e.g. update channel, email settings and so on.

**Comment by xoxys** [comment]
@wkloucek Even If I don't think that's the best approach, I would like to merge it as a workaround... I have added the change to missing files, can you do a quick review and add your opinion?

**Review by wkloucek — APPROVED** [review]
Log level still defaults to WARN (2) after this change according to https://doc.owncloud.com/server/next/admin_manual/configuration/server/logging/logging_configuration.html#parameters

**Pull request merged**
